// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"ganjineh-auth/internal/config"
	"ganjineh-auth/internal/database"
	"ganjineh-auth/internal/handlers"
	"ganjineh-auth/internal/repositories"
	"ganjineh-auth/internal/routes"
	"ganjineh-auth/internal/server"
	"ganjineh-auth/internal/services"
	"ganjineh-auth/internal/utils"
	"github.com/gofiber/fiber/v2"
)

// Injectors from wire.go:

func InitializeUserHandler() (*server.FiberServer, error) {
	app := provideFiberApp()
	structConfig := config.LoadConfig()
	servicePostgresStruct := database.NewPostgresConnction(structConfig)
	serviceRedisStruct := database.NewRedisConnection(structConfig)
	redisOTPRepositoryInterface := repositories.NewRedisRepository(serviceRedisStruct)
	queries := repositories.NewQueries(servicePostgresStruct)
	container := repositories.NewContainer(redisOTPRepositoryInterface, queries)
	otpPkgStruct := utils.NewOTPPkgService(structConfig)
	otpServiceInterface := services.NewOTPService(redisOTPRepositoryInterface, otpPkgStruct)
	jwtPkgStruct := utils.NewJWTPkgService(structConfig)
	authServiceInterface := services.NewAuthService(otpServiceInterface, queries, jwtPkgStruct, redisOTPRepositoryInterface)
	validate := utils.NewValidator()
	authHandlerStruct := handlers.NewAuthHandler(authServiceInterface, validate)
	authRoutesStruct := routes.NewAuthRoutes(authHandlerStruct)
	v := routes.ProvideRouteRegistrars(authRoutesStruct)
	routeContainer := routes.NewRouteContainer(v...)
	fiberServer := server.New(app, servicePostgresStruct, serviceRedisStruct, container, routeContainer)
	return fiberServer, nil
}

// wire.go:

func provideFiberApp() *fiber.App {
	return fiber.New(fiber.Config{
		ServerHeader: "ganjineh-auth",
		AppName:      "ganjineh-auth",
	})
}
