// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"ganjineh-auth/internal/config"
	"ganjineh-auth/internal/database"
	"ganjineh-auth/internal/handlers"
	"ganjineh-auth/internal/middleware"
	"ganjineh-auth/internal/repositories"
	"ganjineh-auth/internal/routes"
	"ganjineh-auth/internal/server"
	"ganjineh-auth/internal/services"
	"ganjineh-auth/internal/utils"
	"ganjineh-auth/pkg"
)

// Injectors from wire.go:

func InitializeUserHandler() (*server.FiberServer, error) {
	structConfig := config.LoadConfig()
	servicePostgresStruct := database.NewPostgresConnction(structConfig)
	serviceRedisStruct := database.NewRedisConnection(structConfig)
	redisOTPRepositoryInterface := repositories.NewRedisRepository(serviceRedisStruct)
	queries := repositories.NewQueries(servicePostgresStruct)
	redisBlackListRepositoryInterface := repositories.NewRedisBlackListRepository(serviceRedisStruct)
	redisPermissionRepositoryInterface := repositories.NewRedisPermissionRepository(serviceRedisStruct)
	container := repositories.NewContainer(redisOTPRepositoryInterface, queries, redisBlackListRepositoryInterface, redisPermissionRepositoryInterface)
	jwtPkgStruct := utils.NewJWTPkgService(structConfig)
	jwtMiddleware := middleware.NewJWTMiddleware(jwtPkgStruct)
	blackListMiddleware := middleware.NewBlackListMiddleware(redisBlackListRepositoryInterface)
	permissionMiddleware := middleware.NewPermissionMiddleware(redisPermissionRepositoryInterface)
	registerMiddleware := middleware.NewRegisterMiddleware(jwtPkgStruct)
	middlewareDependencies := middleware.NewMiddlewareDependencies(jwtMiddleware, blackListMiddleware, permissionMiddleware, registerMiddleware)
	otpPkgStruct := utils.NewOTPPkgService(structConfig)
	otpServiceInterface := services.NewOTPService(redisOTPRepositoryInterface, otpPkgStruct)
	authServiceInterface := services.NewAuthService(otpServiceInterface, queries, jwtPkgStruct, redisOTPRepositoryInterface)
	validate := utils.NewValidator()
	authHandlerStruct := handlers.NewAuthHandler(authServiceInterface, validate)
	authRoutesStruct := routes.NewAuthRoutes(authHandlerStruct, middlewareDependencies)
	handlerServer := server.ProvideGraphQLHandler()
	graphQLRoutesStruct := routes.NewGraphQLRoutes(handlerServer, middlewareDependencies)
	v := routes.ProvideRouteRegistrars(authRoutesStruct, graphQLRoutesStruct)
	routeContainer := routes.NewRouteContainer(middlewareDependencies, v...)
	errorHandler := pkg.NewErrorHandler()
	reWriteRoleServiceInterface := services.NewRewriteRoleService(queries, redisPermissionRepositoryInterface)
	startupServiceInterface := services.NewStartupService(reWriteRoleServiceInterface)
	fiberServer := server.New(servicePostgresStruct, serviceRedisStruct, container, routeContainer, errorHandler, startupServiceInterface)
	return fiberServer, nil
}
