// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: errors_queries.sql

package db

import (
	"context"
)

const insertError = `-- name: InsertError :exec
INSERT INTO errors (http_code,status_code, message, stack_trace, endpoint, request_body)
VALUES ($1, $2, $3, $4, $5,
    COALESCE($6, '{}'::jsonb))
`

type InsertErrorParams struct {
	HttpCode   int32       `json:"http_code"`
	StatusCode int32       `json:"status_code"`
	Message    string      `json:"message"`
	StackTrace *string     `json:"stack_trace"`
	Endpoint   *string     `json:"endpoint"`
	Column6    interface{} `json:"column_6"`
}

func (q *Queries) InsertError(ctx context.Context, arg InsertErrorParams) error {
	_, err := q.db.Exec(ctx, insertError,
		arg.HttpCode,
		arg.StatusCode,
		arg.Message,
		arg.StackTrace,
		arg.Endpoint,
		arg.Column6,
	)
	return err
}
