// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: iam_queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeuser = `-- name: Activeuser :exec
UPDATE users 
SET 
    status = 'active'
WHERE id = $1
`

func (q *Queries) Activeuser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activeuser, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone_number, first_name, last_name, gender, role_id, is_phone_verified)
VALUES ($1, $2, $3, $4, $5, true)
ON CONFLICT (phone_number) DO NOTHING
RETURNING id, phone_number, first_name, last_name, role_id
`

type CreateUserParams struct {
	PhoneNumber string     `json:"phone_number"`
	FirstName   string     `json:"first_name"`
	LastName    string     `json:"last_name"`
	Gender      GenderEnum `json:"gender"`
	RoleID      int32      `json:"role_id"`
}

type CreateUserRow struct {
	ID          pgtype.UUID `json:"id"`
	PhoneNumber string      `json:"phone_number"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	RoleID      int32       `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.PhoneNumber,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.RoleID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.RoleID,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users 
SET 
    status = 'inactive'
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT
    name,
    permission_codes,
    is_system_role
FROM roles
ORDER BY id
`

type GetAllRolesRow struct {
	Name            string   `json:"name"`
	PermissionCodes []string `json:"permission_codes"`
	IsSystemRole    bool     `json:"is_system_role"`
}

func (q *Queries) GetAllRoles(ctx context.Context) ([]GetAllRolesRow, error) {
	rows, err := q.db.Query(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllRolesRow{}
	for rows.Next() {
		var i GetAllRolesRow
		if err := rows.Scan(&i.Name, &i.PermissionCodes, &i.IsSystemRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT 
    name
FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getSession = `-- name: GetSession :one
SELECT 
    id,
    user_id,
    refresh_token_hash,
    refresh_token_expires_at,
    status
FROM user_sessions 
WHERE id = $1 AND user_id = $2
`

type GetSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetSessionRow struct {
	ID                    pgtype.UUID       `json:"id"`
	UserID                pgtype.UUID       `json:"user_id"`
	RefreshTokenHash      string            `json:"refresh_token_hash"`
	RefreshTokenExpiresAt time.Time         `json:"refresh_token_expires_at"`
	Status                SessionStatusType `json:"status"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.UserID)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.Status,
	)
	return i, err
}

const getUserActiveSessions = `-- name: GetUserActiveSessions :many
SELECT id 
FROM user_sessions 
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetUserActiveSessions(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT 
    u.id,
    u.status,
    CASE 
        WHEN u.status = 'active' THEN u.phone_number
        ELSE NULL 
    END AS phone_number,
    CASE 
        WHEN u.status = 'active' THEN u.first_name 
        ELSE NULL 
    END AS first_name,
    CASE 
        WHEN u.status = 'active' THEN u.last_name 
        ELSE NULL 
    END AS last_name,
    CASE 
        WHEN u.status = 'active' THEN r.name 
        ELSE NULL 
    END AS main_role_name,
    CASE 
        WHEN u.status = 'active' THEN 
            COALESCE(
                json_agg(
                    json_build_object(
                        'company_id', uc.company_id,
                        'role_name', r2.name
                    )
                ) FILTER (WHERE uc.id IS NOT NULL),
                '[]'
            )
        ELSE '[]'::json
    END AS company_roles
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
LEFT JOIN user_companies uc ON uc.user_id = u.id AND uc.is_active = true
LEFT JOIN companies c ON uc.company_id = c.id
LEFT JOIN roles r2 ON uc.role_id = r2.id
WHERE u.phone_number = $1
GROUP BY u.id, u.status, r.name
`

type GetUserByPhoneRow struct {
	ID           pgtype.UUID `json:"id"`
	Status       UserStatus  `json:"status"`
	PhoneNumber  interface{} `json:"phone_number"`
	FirstName    interface{} `json:"first_name"`
	LastName     interface{} `json:"last_name"`
	MainRoleName interface{} `json:"main_role_name"`
	CompanyRoles []byte      `json:"company_roles"`
}

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.MainRoleName,
		&i.CompanyRoles,
	)
	return i, err
}

const insertUserSession = `-- name: InsertUserSession :exec
INSERT INTO user_sessions (
    id,
    user_id,
    refresh_token_hash,
    refresh_token_created_at,
    refresh_token_expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertUserSessionParams struct {
	ID                    pgtype.UUID `json:"id"`
	UserID                pgtype.UUID `json:"user_id"`
	RefreshTokenHash      string      `json:"refresh_token_hash"`
	RefreshTokenCreatedAt time.Time   `json:"refresh_token_created_at"`
	RefreshTokenExpiresAt time.Time   `json:"refresh_token_expires_at"`
}

func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error {
	_, err := q.db.Exec(ctx, insertUserSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.RefreshTokenCreatedAt,
		arg.RefreshTokenExpiresAt,
	)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions 
SET 
    status = 'revoked',
    revoked_at = NOW(),
    revoked_by = $2
WHERE user_id = $1 AND status = 'active'
`

type RevokeAllUserSessionsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	RevokedBy pgtype.UUID `json:"revoked_by"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.UserID, arg.RevokedBy)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions 
SET 
    status = 'revoked',
    revoked_at = NOW(),
    revoked_by = $3
WHERE id = $1 AND user_id = $2
`

type RevokeSessionParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	RevokedBy pgtype.UUID `json:"revoked_by"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID, arg.RevokedBy)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users 
SET 
    password_hash = $2,
    is_password_set = TRUE
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash *string     `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const suspendUser = `-- name: SuspendUser :exec
UPDATE users 
SET 
    status = 'suspended'
WHERE id = $1
`

func (q *Queries) SuspendUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, suspendUser, id)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE user_sessions 
SET 
    refresh_token_hash = $2,
    refresh_token_created_at = $3,
    refresh_token_expires_at = $4,
    last_active = $5
WHERE id = $1
`

type UpdateSessionParams struct {
	ID                    pgtype.UUID `json:"id"`
	RefreshTokenHash      string      `json:"refresh_token_hash"`
	RefreshTokenCreatedAt time.Time   `json:"refresh_token_created_at"`
	RefreshTokenExpiresAt time.Time   `json:"refresh_token_expires_at"`
	LastActive            time.Time   `json:"last_active"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.RefreshTokenHash,
		arg.RefreshTokenCreatedAt,
		arg.RefreshTokenExpiresAt,
		arg.LastActive,
	)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
UPDATE users 
SET 
    phone_number = $2
WHERE id = $1
`

type UpdateUserPhoneParams struct {
	ID          pgtype.UUID `json:"id"`
	PhoneNumber string      `json:"phone_number"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.Exec(ctx, updateUserPhone, arg.ID, arg.PhoneNumber)
	return err
}

const updatedAllUserSessions = `-- name: UpdatedAllUserSessions :exec
UPDATE user_sessions 
SET 
    status = 'updated'
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) UpdatedAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updatedAllUserSessions, userID)
	return err
}
