// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompanyType string

const (
	CompanyTypeOnlineStore       CompanyType = "online_store"
	CompanyTypePhysicalStore     CompanyType = "physical_store"
	CompanyTypeMultichannelStore CompanyType = "multichannel_store"
)

func (e *CompanyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyType(s)
	case string:
		*e = CompanyType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyType: %T", src)
	}
	return nil
}

type NullCompanyType struct {
	CompanyType CompanyType `json:"company_type"`
	Valid       bool        `json:"valid"` // Valid is true if CompanyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyType) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyType), nil
}

type GenderEnum string

const (
	GenderEnumMale    GenderEnum = "male"
	GenderEnumFemale  GenderEnum = "female"
	GenderEnumUnknown GenderEnum = "unknown"
)

func (e *GenderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderEnum(s)
	case string:
		*e = GenderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderEnum: %T", src)
	}
	return nil
}

type NullGenderEnum struct {
	GenderEnum GenderEnum `json:"gender_enum"`
	Valid      bool       `json:"valid"` // Valid is true if GenderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GenderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderEnum), nil
}

type SessionStatusType string

const (
	SessionStatusTypeActive  SessionStatusType = "active"
	SessionStatusTypeRevoked SessionStatusType = "revoked"
	SessionStatusTypeUpdated SessionStatusType = "updated"
)

func (e *SessionStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatusType(s)
	case string:
		*e = SessionStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatusType: %T", src)
	}
	return nil
}

type NullSessionStatusType struct {
	SessionStatusType SessionStatusType `json:"session_status_type"`
	Valid             bool              `json:"valid"` // Valid is true if SessionStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatusType), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusInactive  UserStatus = "inactive"
	UserStatusSuspended UserStatus = "suspended"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Company struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	CompanyType CompanyType `json:"company_type"`
	Code        string      `json:"code"`
	ContactInfo []byte      `json:"contact_info"`
	Settings    []byte      `json:"settings"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Error struct {
	ID          int64            `json:"id"`
	HttpCode    int32            `json:"http_code"`
	StatusCode  int32            `json:"status_code"`
	Message     string           `json:"message"`
	StackTrace  *string          `json:"stack_trace"`
	Endpoint    *string          `json:"endpoint"`
	RequestBody []byte           `json:"request_body"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Role struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	PermissionCodes []string           `json:"permission_codes"`
	IsSystemRole    bool               `json:"is_system_role"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	NoID              *string            `json:"no_id"`
	PhoneNumber       string             `json:"phone_number"`
	Email             *string            `json:"email"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	Gender            GenderEnum         `json:"gender"`
	ProfileData       []byte             `json:"profile_data"`
	PasswordHash      *string            `json:"password_hash"`
	Status            UserStatus         `json:"status"`
	RoleID            int32              `json:"role_id"`
	IsPhoneVerified   bool               `json:"is_phone_verified"`
	IsPasswordSet     bool               `json:"is_password_set"`
	IsProfileComplete bool               `json:"is_profile_complete"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserCompany struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	CompanyID  int32       `json:"company_id"`
	RoleID     int32       `json:"role_id"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
	AssignedAt time.Time   `json:"assigned_at"`
	IsActive   bool        `json:"is_active"`
}

type UserSession struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	DeviceInfo            []byte             `json:"device_info"`
	RefreshTokenHash      string             `json:"refresh_token_hash"`
	RefreshTokenCreatedAt time.Time          `json:"refresh_token_created_at"`
	RefreshTokenExpiresAt time.Time          `json:"refresh_token_expires_at"`
	LastActive            time.Time          `json:"last_active"`
	Status                SessionStatusType  `json:"status"`
	RevokedAt             pgtype.Timestamptz `json:"revoked_at"`
	RevokedBy             pgtype.UUID        `json:"revoked_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}
