// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	Activeuser(ctx context.Context, id pgtype.UUID) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeactivateUser(ctx context.Context, id pgtype.UUID) error
	GetAllRoles(ctx context.Context) ([]GetAllRolesRow, error)
	GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error)
	GetUserActiveSessions(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (GetUserByPhoneRow, error)
	InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SuspendUser(ctx context.Context, id pgtype.UUID) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error
	UpdatedAllUserSessions(ctx context.Context, userID pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
